Update porn
tiuxo/hosts pull request #29
Opened 2021-07-12 14:41 UTC by chirag127

Many NSFW domains which are not blocked are added.

2021-07-14 10:41 UTC, glaciers7506 approved these changes

2021-07-20 13:28 UTC, spirillen requested changes

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 xhamster12.desi
curl -I 'http://xhamster12.desi/'
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 20 Jul 2021 13:25:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: stats_id=214439; expires=Tue, 27-Jul-2021 13:25:00 GMT; Max-Age=604800; path=/; domain=.xhamster12.desi; secure; SameSite=None
Srv: main137
Cache-Control: no-cache, no-store, must-revalidate
ETag: 8e7b94a4b872654ec3a09d7f495dee94
Strict-Transport-Security: max-age=86400; preload
Vary: User-Agent
Location: https://xhamster.com
X-Frame-Options: SAMEORIGIN

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 www.porn00.tv
Not enough records... See https://mypdns.org/my-privacy-dns/porn-records/-/issues/112

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 porntn.com
Missing at least 2 records... See: https://mypdns.org/my-privacy-dns/porn-records/-/issues/110

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 hitbdsm.com
Missing at least 4 records, See: https://mypdns.org/my-privacy-dns/porn-records/-/issues/109

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 adultsearch.com
Missing a lot of subdomains.... See: https://mypdns.org/my-privacy-dns/porn-records/-/issues/108

2021-07-20 13:28 UTC, spirillen commented on porn
> +0.0.0.0 xhamster12.desi
This means it should not be in the list

2021-07-20 18:50 UTC, chirag127 commented
Well my reason to create the PR was that this list is used in the nextdns. But seems like now these domains are Already blocked by nextdns.

2021-07-20 18:50 UTC, closed without merging

2021-07-20 20:11 UTC, spirillen commented
Yep @nextdns have chosen to make yet another anti-porn project, rather than collaborate with existing lists.. 

https://github.com/nextdns/metadata/issues/569#issuecomment-860041895

2021-07-20 20:20 UTC, chirag127 commented
Hmm... Till yet they are combining many blocklist. And I think these domains Just got added to one of the included lists.

2021-07-20 20:34 UTC, spirillen commented
Yep, they are all coming from https://mypdns.org/my-privacy-dns/porn-records via https://github.com/Clefspeare13/pornhosts

2021-12-13 18:40 UTC, Rexadev commented
> Yep @nextdns have chosen to make yet another anti-porn project, rather than collaborate with existing lists..

NextDNS is using mypdns.org but doesn't show in json. After I pull request 171gifs you added it to mypdns and they blocked it. Only blocklist nextdns have is PornAway (1 is notupdated other 2 are combined into the 4th one) .and it doesn't have 171gifs

2021-12-13 18:48 UTC, spirillen commented
> I don't know how Clefspeare13/pornhosts is blocked

Hmm actually a good question. I haven't though of how the movement (Do to take down) of that repo infected this repo, but I would as such assume they have upgraded there import path to match the new location.